--query part2
--tuple varaiable

SELECT PRODUCT_ID AS PRODUCTS_CODE , A.PRODUCT_NAME, A.STOCK_COUNT-1 AS STOCK_AFTER_SELL, B.PAYMENT_DATE
FROM PRODUCTS_INFO A, PAYMENT_INFO B
WHERE B.PRODUCT = A.PRODUCT_ID AND STOCK = 'YES'


SELECT NAME AS BUYES_NAME, A.ADDRESS, C.PRODUCT_NAME, B.PAYMENT_ID, B.TOTAL_AMOUNT
FROM CUSTOMER_INFO A, PAYMENT_INFO B ,PRODUCTS_INFO C
WHERE B.PRODUCT = C.PRODUCT_ID AND A.CUSTOMER_ID = B.CUSTOMER_ID


--subqurry

SELECT EMPLOYEE_ID, EMPLOYEE_INFO.NAME, EMPLOYEE_INFO.ROLE
FROM EMPLOYEE_INFO
WHERE EMPLOYEE_ID IN 
(SELECT BRANCH_INFO.MANAGER_ID
FROM BRANCH_INFO
WHERE NUMBER_OF_EMPLOYEE > 10);


--create view

CREATE VIEW SALESMAN_INFO AS
SELECT EMPLOYEE_ID  AS SALESMAN_ID, NAME, PHONE_NUMBER , ADDRESS, SALARY
FROM EMPLOYEE_INFO
WHERE ROLE = 'SALESMAN'


CREATE VIEW SALESMAN_BRANCH01 AS
SELECT A.EMPLOYEE_ID  AS SALESMAN_ID, A.NAME, B.BRANCH_ID, B.BRANCH_NAME, B.MANAGER_NAME AS WORKS_UNDER, A.PHONE_NUMBER , A.ADDRESS, A.SALARY
FROM EMPLOYEE_INFO A, BRANCH_INFO B
WHERE A.ROLE = 'SALESMAN' AND B.BRANCH_ID = 'MIR01' AND A.BRANCH_ID = 'MIR01'


CREATE VIEW MANAGER_INFO AS
SELECT A.EMPLOYEE_ID AS SALESMAN_ID, A.NAME,B.BRANCH_ID, B.BRANCH_NAME, A.PHONE_NUMBER, A.ADDRESS AS MANAGER_ADDRESS, A.SALARY
FROM EMPLOYEE_INFO A, BRANCH_INFO B
WHERE ROLE = 'MANAGER' AND A.BRANCH_ID = B.BRANCH_ID


CREATE VIEW ONE_DAY_SELLS AS
SELECT A.PAYMENT_ID, A.PAYMENT_DATE, A.TOTAL_AMOUNT, B.CATEGORY, B.PRODUCT_NAME
FROM PAYMENT_INFO A, PRODUCTS_INFO B
WHERE A.PAYMENT_DATE = '12-JUN-22' AND A.PRODUCT = B.PRODUCT_ID


--view query

SELECT A.NAME , A.SALARY * 2, B.BRANCH_NAME, B.WORKS_UNDER
FROM SALESMAN_INFO A, SALESMAN_BRANCH01 B
WHERE A.SALESMAN_ID = B.SALESMAN_ID


CREATE VIEW TEST01 AS
SELECT EMPLOYEE_ID, NAME, PHONE_NUMBER,ADDRESS, SALARY
FROM EMPLOYEE_INFO
WHERE SALARY = 40000 AND ROLE = 'MANAGER'
WITH CHECK OPTION;


INSERT INTO TEST01 VALUES('M011','TAMANNA AKTER','01900000099','MIRPUR,DHAKA',40000);


UPDATE TEST01 
SET NAME = 'NULL', PHONE_NUMBER = 'NULL', ADDRESS = 'NULL'
WHERE EMPLOYEE_ID = 'M011'


DELETE FROM TEST01 WHERE EMPLOYEE_ID = 'M011'
